## 1. 导入相关包

In [1]:
import tensorflow as tf
tfe = tf.contrib.eager
# 启动eager execution模式
tf.enable_eager_execution()

import numpy as np
import matplotlib.pyplot as plt
import time

## 2. 设置超参数

In [2]:
# 总时间步长 = 图像行数
TIME_STEPS = 28
# 输入维度  = 图像列数
INPUT_SIZE = 28
# 隐含状态单元数
HIDDEN_SIZE = 50
# 输出维度  = 图像类别数
OUTPUT_SIZE = 10

# Batch size
BATCH_SIZE = 50
# epoches数
NUM_EPOCH = 1

# 学习率
LEARNING_RATE = 0.001

## 3. 准备数据

### 3.1. 导入数据集

In [3]:
(x_train, y_train), (x_test, y_test) = tf.keras.datasets.mnist.load_data(path='mnist.npz')

print('Training set:')
print('       Data :\t shape:', np.shape(x_train), '\t type:', x_train.dtype)
print('       Label:\t shape:', np.shape(y_train), '\t\t type:', y_train.dtype)
print('Testing set :')
print('       Data :\t shape:', np.shape(x_test), '\t type:', x_test.dtype)
print('       Label:\t shape:', np.shape(y_test), '\t\t type:', y_test.dtype)

Training set:
       Data :	 shape: (60000, 28, 28) 	 type: uint8
       Label:	 shape: (60000,) 		 type: uint8
Testing set :
       Data :	 shape: (10000, 28, 28) 	 type: uint8
       Label:	 shape: (10000,) 		 type: uint8


### 3.2. 数据预处理

In [4]:
# 转化为 float 型并归一化
x_train = x_train.astype(np.float32)/255
x_test = x_test.astype(np.float32)/255
print(np.shape(x_train), np.shape(x_test))

# 标签转化为 ont hot 向量
y_train = tf.one_hot(y_train, 10, dtype=tf.float32)
y_test = tf.one_hot(y_test, 10, dtype=tf.float32)
print(y_train, y_test)

(60000, 28, 28) (10000, 28, 28)
tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]], shape=(60000, 10), dtype=float32) tf.Tensor(
[[0. 0. 0. ... 1. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(10000, 10), dtype=float32)


### 3.3. 生成Dataset对象

In [23]:
# 生成用于训练的Dataset对象
TrainDataset = tf.data.Dataset.from_tensor_slices((x_train, y_train))
# 按buffer_size打乱
TrainDataset = TrainDataset.shuffle(buffer_size=5000)
# Batch size
TrainDataset = TrainDataset.batch(BATCH_SIZE, drop_remainder=True)

# 生成用于测试的Dataset对象
TestDataset = tf.data.Dataset.from_tensor_slices((x_test, y_test)).batch(BATCH_SIZE, drop_remainder=True)

## 4. 创建网络

### 4.1. 创建RNN

In [33]:
class Model(tf.keras.Model):
    def __init__(self, hidden_size, output_size):
        super(Model, self).__init__()
        self.units = hidden_size
        
        self.rnn = tf.keras.layers.SimpleRNN(units = hidden_size,   # units = HIDDEN_SIZE
                                             unroll = True,         # 预分配输入的形状，这里我们设置为
                                             # [NUM_BATCH, TIME_STEPS, INPUT_SIZE]。可以加快训练，但
                                             # 会消耗大量内存，只有当序列较短时适用。
                                             stateful = False,      # 当前batch的最后一个状态不会用于
                                             # 下一个batch的初始状态，只有当数据是依次截断的时候适用。
                                             return_sequences = False# 只返回最后一个时间的状态
                                            )

        self.fc = tf.keras.layers.Dense(output_size)
        # 如果需要输出概率，添加：
        # self.softmax = tf.keras.layers.Softmax()

    def call(self, inputs):
        # output shape == (BATCH_SIZE, HIDDEN_SIZE) 
        output = self.rnn(inputs)

        # output shape == (BATCH_SIZE, OUTPUT_SIZE)
        prediction = self.fc(output)
        
        # 如果需要输出概率，添加：
        #     prediction = self.softmax(fc)
        return prediction

### 4.2. 损失函数

In [30]:
def Loss(y_pred, y_true):
    '''
    Input:
        y_pred - [BATCH_SIZE, NUM_CLASS]
        y      - [BATCH_SIZE, NUM_CLASS]
    '''    
    # 如果标签不是one-hot向量，使用sparse_softmax_cross_entropy
    return tf.losses.softmax_cross_entropy(onehot_labels=y_true, logits=y_pred)

### 4.3. 评估函数

In [8]:
def Accuracy(y_pred, y_true):
    '''
    Input:
        y_pred - [BATCH_SIZE, NUM_CLASS]
        y      - [BATCH_SIZE, NUM_CLASS]
    '''
    accuracy = tf.reduce_mean(tf.cast(tf.equal(tf.argmax(y_true,1), tf.argmax(y_pred,1)),tf.float32))
    return accuracy

### 4.4. 优化器

In [9]:
# 使用adam优化器，默认参数
optimizer = tf.train.AdamOptimizer(LEARNING_RATE)

### 4.5. 训练

In [34]:
model = Model(HIDDEN_SIZE, OUTPUT_SIZE)

# 初始化模型才可以：
#     1. 调用model.summary() 
#     2. 调用reset_states()
# 在tf 1.11可用直接调用model.build(INPUT_SHAPE) 来初始化模型，但
# 在早期版本，可能需要输入一个哑变量：
#    dummy_x = tf.zeros((BATCH_SIZE, TIME_STEPS, INPUT_SIZE))
#    model._set_inputs(dummy_x)

# 若 unroll=True:
model.build((NUM_BATCH, TIME_STEPS, INPUT_SIZE))
# 若 unroll=False:
#    model.build((None, TIME_STEPS, INPUT_SIZE))
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
simple_rnn_3 (SimpleRNN)     multiple                  3950      
_________________________________________________________________
dense_3 (Dense)              multiple                  510       
Total params: 4,460
Trainable params: 4,460
Non-trainable params: 0
_________________________________________________________________


In [35]:
# 开始训练
for epoch in range(NUM_EPOCH):
    start = time.time()
    
    # 在每个epoch开始时初始化隐藏状态，一开始为None
    hidden = model.reset_states()
    
    for (batch, (x, y)) in enumerate(TrainDataset):
        with tf.GradientTape() as tape:
            # 前向传播
            y_pred = model(x)
            loss = Loss(y_pred, y)
        # 反向传播
        grads = tape.gradient(loss, model.variables)
        optimizer.apply_gradients(zip(grads, model.variables))

        if batch % 500 == 0:
            print ('Epoch {} Batch {} Loss {:.4f}'.format(epoch+1,
                                                          batch,
                                                          loss))
           
    print ('Epoch {} Loss {:.4f}'.format(epoch+1, loss))
    print ('Time taken for 1 epoch {} sec\n'.format(time.time() - start))
    
    
    # 若 unroll=True:
    cost = []
    accuracy = []    
    for x, y in TestDataset:
        y_pred = model(x)
        cost.append(Loss(y_pred, y))
        accuracy.append(Accuracy(y_pred, y))
    # For若 unroll=False:
    #    y_pred = model(x_test)
    #    cost = Loss(y_pred, y_test)
    #    accuracy = Accuracy(y_pred, y_test)
    print('test cost: ', np.mean(cost), 'test accuracy: ', np.mean(accuracy))

Epoch 1 Batch 0 Loss 2.4750
Epoch 1 Batch 500 Loss 0.5501
Epoch 1 Batch 1000 Loss 0.4739
Epoch 1 Loss 0.1727
Time taken for 1 epoch 42.26512694358826 sec

test cost:  0.30884752 test accuracy:  0.90799993
