## 1. Import Related Modules and Packages

In [1]:
import tensorflow as tf
tfe = tf.contrib.eager
# Enable eager execution mode
tf.enable_eager_execution()

import numpy as np
import matplotlib.pyplot as plt

## 2. Hyperparameters

In [4]:
# A time step inputs one row of a image
# Number of time steps = number of rows
TIME_STEPS = 28
# Input  size = number of columns
INPUT_SIZE = 28
# Size of hidden states
HIDDEN_SIZE = 50
# Output size = number of classes
OUTPUT_SIZE = 10

# Batch size
BATCH_SIZE = 50
# Number of batches
NUM_BATCH = len(x_train)//BATCH_SIZE
# Number of epoches
NUM_EPOCH = 20

# Learning rate
LEARNING_RATE = 0.001

## 3. Prepare for Data

### 3.1. Load Data

In [2]:
(x_train, y_train), (x_test, y_test) = tf.keras.datasets.mnist.load_data(path='mnist.npz')

print('Training set:')
print('       Data :\t shape:', np.shape(x_train), '\t type:', x_train.dtype)
print('       Label:\t shape:', np.shape(y_train), '\t\t type:', y_train.dtype)
print('Testing set :')
print('       Data :\t shape:', np.shape(x_test), '\t type:', x_test.dtype)
print('       Label:\t shape:', np.shape(y_test), '\t\t type:', y_test.dtype)

Training set:
       Data :	 shape: (60000, 28, 28) 	 type: uint8
       Label:	 shape: (60000,) 		 type: uint8
Testing set :
       Data :	 shape: (10000, 28, 28) 	 type: uint8
       Label:	 shape: (10000,) 		 type: uint8


### 3.2. Data Preprocessing

In [3]:
# 转化为 float 型并归一化
x_train = x_train.reshape(60000,-1).astype(np.float32)/255
x_test = x_test.reshape(10000,-1).astype(np.float32)/255
print(np.shape(x_train), np.shape(x_test))

# 标签转化为 ont hot 向量
y_train = tf.one_hot(y_train, 10, dtype=tf.float32)
y_test = tf.one_hot(y_test, 10, dtype=tf.float32)
print(y_train, y_test)

(60000, 784) (10000, 784)
tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]], shape=(60000, 10), dtype=float32) tf.Tensor(
[[0. 0. 0. ... 1. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(10000, 10), dtype=float32)


## 4. Build RNN

### 4.1. Build RNN

### 4.2. Loss Function

### 4.3. Accuracy Evaluator

### 4.4. Training